ALTER TABLE contracts
  ADD COLUMN IF NOT EXISTS deposit_amount TEXT,
  ADD COLUMN IF NOT EXISTS stake_amount TEXT,
  ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ends_at TIMESTAMPTZ;
